apiVersion: v1
kind: Service
metadata:
  name: blazegraph
  labels:
    app: blaze
spec:
  type: NodePort
  selector:
    app: blaze
  ports:
    - port: 80
      targetPort: 9999
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: blazegraph
spec:
  serviceName: blazegraph
  replicas: 1
  selector:
    matchLabels:
      app: blaze
  template:
    metadata:
      labels:
        app: blaze
    spec:
      containers:
        - name: blazegraph
          image: bluebrain/blazegraph-nexus
          ports:
            - containerPort: 9999
              name: blazegraph
  volumeClaimTemplates:
    - metadata:
        name: blaze-pv-claim
      spec:
        storageClassName: managed-csi
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
