---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bbp-ou-nise-production
generatorOptions:
  disableNameSuffixHash: true # this flag is used to avoid creation of new configmap, instead it will be modified when file context is changed
configMapGenerator:
  - name: delta-config
    files:
      - delta.conf
